#!/bin/bash

clear

mkdir ~/Nameles/

# getting the user choice for type of installation
echo -e " "
echo -e " +---------------------------------+"
echo -e " | Welcome to Nameles Installation |"
echo -e " +---------------------------------+"
echo -e
read -p " INSTALLATION MODE: 'single' or 'multi' : " CHOICE

case $CHOICE in
    [single]* ) echo -e "\n Deploying single-system \n"; MODE=(single);;
    [multi]* ) echo -e "\n Deploying single-system \n"; MODE=(multi);;
    * ) echo "You did not make an accepted choice";;
esac


# get the docker compose file for single

if [ "$MODE" == single ]; then

    wget https://raw.githubusercontent.com/Nameles-Org/Nameles/master/docker-compose.yml
    mv docker-compose.yml ~/Nameles/nameles-docker-compose.yml
fi
# get the docker compose file for multi

if [ "$MODE" == multi ];

    wget https://raw.githubusercontent.com/Nameles-Org/data-processing-module/master/docker-compose.yml
    mv docker-compose.yml ~/Nameles/data-docker-compose.yml

    wget https://raw.githubusercontent.com/Nameles-Org/scoring-module/master/docker-compose.yml
    mv docker-compose.yml ~/Nameles/scoring-docker-compose.yml

    wget https://raw.githubusercontent.com/Nameles-Org/dsp-emulator/master/docker-compose.yml
    mv docker-compose.yml ~/Nameles/emulator-docker-compose.yml

fi


clear

echo " "
# getting the user choice for type of installation
read -p " REMOVING OLD VERSION OF DOCKER: This is recommended, are you ok with it? : " yn
case $yn in
    [Yy]* ) sudo apt-get -qq remove docker docker-engine docker.io -y;;
    [Nn]* ) echo "Ok, we're keeping your current docker version. Let's see how it goes.";;
    * ) echo "Please choose Yy or Nn";;
esac

clear

echo ""
echo -e "Starting installation, please wait. This should be over in a few minutes."
echo " "

# update packages 
sudo apt-get -qq update -y

# install linux-extra-image-*
sudo apt-get install linux-image-extra-$(uname -r) -y
sudo apt-get install linux-image-extra-virtual -y

# update packages 
sudo apt-get -qq update -y

# install dependencies
sudo apt-get -qq install apt-transport-https -y
sudo apt-get -qq install ca-certificates -y
sudo apt-get -qq install curl -y
sudo apt-get -qq install software-properties-common -y

# add the docker GPG key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

# test the key fingerprint 
sudo apt-key fingerprint 0EBFCD88

# add the repository / package 
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

# update packages 
sudo apt-get -qq update -y

# and (finally) the actual install
sudo apt-get -qq install docker-ce -y

# download the latest version of docker-compose
sudo curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose

# change the permissions 
sudo chmod +x /usr/local/bin/docker-compose

# add current user to the docker group
sudo usermod -aG docker $USER

# test that docker works ok
docker run hello-world

# verify the docker-compose version 
docker-compose --version

# install psql 
sudo apt-get -qq install postgresql-client -y

# execute compose

if [ "$MODE" == single ]; then

    sudo docker-compose -f ~/Nameles/nameles-docker-compose.yml up

fi 

if [ "$MODE" == multi ]; then 

    echo " "
    echo -e "Run the following commands in this order in separate shells:"
    echo -e "------------------------------------------------------------"
    echo -e "$   sudo docker-compose -f ~/Nameles/data-docker-compose.yml up"
    echo -e "$   sudo docker-compose -f ~/Nameles/scoring-docker-compose.yml up"
    echo -e "$   sudo docker-compose -f ~/Nameles/emulator-docker-compose.yml up"

fi